### ISSUE TITLE
module 'os' has no attribute 'startfile'

### ISSUE THREAD

**Issue by MloDehghani** [misteralipour/Passenerator#1]
Hi I try to use this program but it this no generate any password and give me this error:

```
Traceback (most recent call last):
  File "main.py", line 153, in generate
    os.startfile('passwords.txt')
AttributeError: module 'os' has no attribute 'startfile'
```
how to fix this?

**Comment by misteralipour** [comment]
Hi
Thanks for your issue report
the function "startfile()" doesn't work on unix based systems, so I add a new function to open the output file and it should work now.

**Comment by MloDehghani** [comment]
awesome,
It works well .thank you very much.

**Comment by MloDehghani** [comment]
this issue is ended.
thank god.
